### ISSUE TITLE
`aten.view` not converted?

### ISSUE THREAD

**Issue by jdh8** [tenstorrent/pytorch2.0_ttnn#173]
This list shows that `aten.view` ops are not converted yet.
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/5109168a27bcff95d650d3828e9ce253659dd6e1/docs/cumulative_input_variations.md?plain=1#L118

Intriguingly, we have code that tries to convert `aten.view` to `aten.reshape`.  I guess this means they are stuck as `aten.reshape` right now.
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/5109168a27bcff95d650d3828e9ce253659dd6e1/torch_ttnn/passes/lowering/to_tt_pass.py#L278-L280

**Comment by kevinwuTT** [comment]
Yeah `aten.view` needs dedicated effort to lower. I previously made a change to temporarily convert `aten.view` to `aten.reshape` because `aten.view` never makes a copy when reshaping tensors. This becomes problematic when the input to `aten.view` was lowered to TTNN because `aten.view` doesn't know how to handle the device memory. `aten.reshape` however will make a copy if it determines that it needs to, so I added that conversion so some of the models will still have some fallback.
